version: "3.8"

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      MONGO_URI: mongodb://mongodb:27017/chat-service
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./backend:/app
  react-app:
    build:
      context: ./frontend
    container_name: react-app
    ports:
      - "3001:3000"
    depends_on:
      - app
volumes:
  mongo-data:
