version: "3.8"

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"

  backend-app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      MONGO_URI: mongodb://mongodb:27017/chat-service
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./backend:/app
  frontend-app:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "8080:8080"
    depends_on:
      - backend-app
volumes:
  mongo-data:
